# -*- coding: utf-8 -*-
"""RobertaBiLSTMAttn(97).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcKToyrhoI5gm2I2fBj-uZg0edzoAHjb
"""

!pip install -q transformers scikit-learn accelerate

import os, random, math, re
from pathlib import Path
from typing import List
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.utils.class_weight import compute_class_weight
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel, get_linear_schedule_with_warmup
from tqdm.auto import tqdm

# Device + reproducibility
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
if device.type == "cuda":
    torch.cuda.manual_seed_all(SEED)

# Config (tweak as needed)
MODEL_NAME = "roberta-base"   # roberta tokenizer + embeddings
MAX_LEN = 128
BATCH_SIZE = 64
K_FOLDS = 5
EPOCHS = 4
LR = 2e-5
WEIGHT_DECAY = 1e-5
PATIENCE = 2
TARGET_ACC = 0.98   # early stop per-fold target (data-dependent)
NUM_WORKERS = 2

DATA_PATH = "/content/Final_Dataset(Thesis) - Sheet1 (2).csv"
assert Path(DATA_PATH).exists(), f"Dataset not found at {DATA_PATH}"

df = pd.read_csv(DATA_PATH, engine='python', on_bad_lines='skip')
print("Raw shape:", df.shape)
print("Columns:", df.columns.tolist())

# Column names expected: 'text' and 'label' (as in your upload)
TEXT_COL = "text"
LABEL_COL = "label"

# Drop rows with missing text
before = len(df)
df = df.dropna(subset=[TEXT_COL]).reset_index(drop=True)
print(f"Dropped {before - len(df)} rows with missing text. New shape: {df.shape}")

# Basic dedup (optional)
before = len(df)
df = df.drop_duplicates(subset=[TEXT_COL]).reset_index(drop=True)
print(f"Dropped {before - len(df)} duplicate texts. New shape: {df.shape}")

# Inspect class balance
print("Label value counts:\n", df[LABEL_COL].value_counts())

# Preprocess function: lowercase + remove special characters (keeps basic punctuation)
def preprocess_text(s: str) -> str:
    s = str(s)
    s = s.strip().lower()
    # remove unwanted characters (keep letters, digits, basic punctuation)
    s = re.sub(r"[^a-z0-9\s\.\,\!\?\-']", " ", s)
    s = re.sub(r"\s{2,}", " ", s)
    return s

df[TEXT_COL] = df[TEXT_COL].apply(preprocess_text)

# Label encoding
le = LabelEncoder()
df['label_encoded'] = le.fit_transform(df[LABEL_COL])
NUM_LABELS = len(le.classes_)
print("Classes:", le.classes_, " -> NUM_LABELS:", NUM_LABELS)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)

class TextDataset(Dataset):
    def __init__(self, texts: List[str], labels: List[int], tokenizer, max_len: int = 128):
        self.encodings = tokenizer(
            texts,
            truncation=True,
            padding='max_length',
            max_length=max_len,
            return_tensors='pt'
        )
        self.labels = torch.tensor(labels, dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}  # input_ids, attention_mask, (token_type_ids maybe)
        item['labels'] = self.labels[idx]
        return item

print("Tokenizer loaded. Example tokens:", tokenizer.tokenize("This is a test"))

class RobertaBiLSTMAttn(nn.Module):
    def __init__(self, model_name: str, lstm_hidden: int = 256, lstm_layers: int = 1,
                 dropout: float = 0.2, num_labels: int = 2):
        super().__init__()
        self.roberta = AutoModel.from_pretrained(model_name)
        bert_hidden_size = self.roberta.config.hidden_size
        self.lstm = nn.LSTM(input_size=bert_hidden_size,
                            hidden_size=lstm_hidden,
                            num_layers=lstm_layers,
                            batch_first=True,
                            bidirectional=True,
                            dropout=dropout if lstm_layers > 1 else 0.0)
        self.attn_fc = nn.Linear(lstm_hidden * 2, 1)
        self.classifier = nn.Sequential(
            nn.Dropout(dropout),
            nn.Linear(lstm_hidden * 2, num_labels)
        )

    def forward(self, input_ids, attention_mask):
        # Roberta outputs
        out = self.roberta(input_ids=input_ids, attention_mask=attention_mask, return_dict=True)
        seq_emb = out.last_hidden_state                       # (batch, seq_len, hidden)
        lstm_out, _ = self.lstm(seq_emb)                      # (batch, seq_len, hidden*2)
        attn_scores = self.attn_fc(lstm_out).squeeze(-1)      # (batch, seq_len)
        mask = attention_mask == 1
        neg_inf = -1e9
        attn_scores = torch.where(mask, attn_scores, torch.tensor(neg_inf, device=attn_scores.device))
        attn_weights = torch.softmax(attn_scores, dim=1).unsqueeze(-1)  # (batch, seq_len, 1)
        pooled = (lstm_out * attn_weights).sum(dim=1)         # (batch, hidden*2)
        logits = self.classifier(pooled)
        return logits

from torch.cuda.amp import autocast, GradScaler

def train_one_epoch(model, dataloader, optimizer, scheduler, loss_fn, device, scaler=None):
    model.train()
    total_loss = 0.0
    preds, targets = [], []
    for batch in tqdm(dataloader, desc="train"):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        with torch.cuda.amp.autocast(enabled=(scaler is not None)):
            logits = model(input_ids=input_ids, attention_mask=attention_mask)
            loss = loss_fn(logits, labels)

        if scaler is not None:
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer); scaler.update()
            optimizer.zero_grad()
        else:
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step(); optimizer.zero_grad()

        if scheduler is not None:
            scheduler.step()

        total_loss += loss.item() * input_ids.size(0)
        batch_preds = torch.argmax(logits, dim=1).detach().cpu().numpy()
        preds.extend(batch_preds)
        targets.extend(labels.detach().cpu().numpy())

    avg_loss = total_loss / len(dataloader.dataset)
    acc = accuracy_score(targets, preds)
    return avg_loss, acc

def evaluate(model, dataloader, loss_fn, device):
    model.eval()
    total_loss = 0.0
    preds, targets = [], []
    with torch.no_grad():
        for batch in tqdm(dataloader, desc="eval"):
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)
            logits = model(input_ids=input_ids, attention_mask=attention_mask)
            loss = loss_fn(logits, labels)
            total_loss += loss.item() * input_ids.size(0)
            batch_preds = torch.argmax(logits, dim=1).detach().cpu().numpy()
            preds.extend(batch_preds)
            targets.extend(labels.detach().cpu().numpy())

    avg_loss = total_loss / len(dataloader.dataset)
    acc = accuracy_score(targets, preds)
    precision, recall, f1, _ = precision_recall_fscore_support(targets, preds, average='weighted', zero_division=0)
    return avg_loss, acc, precision, recall, f1

texts = df[TEXT_COL].astype(str).tolist()
labels = df['label_encoded'].astype(int).tolist()

# compute class weights (for CrossEntropyLoss)
classes = np.unique(labels)
cw = compute_class_weight(class_weight='balanced', classes=classes, y=labels)
class_weights = torch.tensor([cw[np.where(classes==c)[0][0]] for c in range(len(classes))], dtype=torch.float).to(device)
print("Class weights:", class_weights.tolist())

skf = StratifiedKFold(n_splits=K_FOLDS, shuffle=True, random_state=SEED)
fold_metrics = []

for fold, (train_idx, val_idx) in enumerate(skf.split(texts, labels), 1):
    print(f"\n=== Fold {fold}/{K_FOLDS} ===")
    train_texts = [texts[i] for i in train_idx]; train_labels = [labels[i] for i in train_idx]
    val_texts = [texts[i] for i in val_idx]; val_labels = [labels[i] for i in val_idx]

    train_ds = TextDataset(train_texts, train_labels, tokenizer, max_len=MAX_LEN)
    val_ds = TextDataset(val_texts, val_labels, tokenizer, max_len=MAX_LEN)
    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS, pin_memory=True)
    val_loader = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)

    model = RobertaBiLSTMAttn(model_name=MODEL_NAME, lstm_hidden=256, lstm_layers=1, dropout=0.2, num_labels=NUM_LABELS).to(device)

    # Loss with class weights
    if NUM_LABELS > 1:
        loss_fn = nn.CrossEntropyLoss(weight=class_weights)
    else:
        loss_fn = nn.BCEWithLogitsLoss()

    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
    total_steps = len(train_loader) * EPOCHS
    warmup_steps = max(1, int(0.05 * total_steps))
    scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=warmup_steps, num_training_steps=total_steps)

    scaler = torch.cuda.amp.GradScaler() if device.type == "cuda" else None

    best_val_metric = 0.0
    best_epoch = -1
    patience_counter = 0
    # track best model path
    best_model_path = f"best_model_fold{fold}.pt"

    for epoch in range(1, EPOCHS + 1):
        print(f"\nFold {fold} | Epoch {epoch}/{EPOCHS}")
        train_loss, train_acc = train_one_epoch(model, train_loader, optimizer, scheduler, loss_fn, device, scaler=scaler)
        val_loss, val_acc, val_prec, val_rec, val_f1 = evaluate(model, val_loader, loss_fn, device)
        print(f"Train loss={train_loss:.4f} acc={train_acc:.4f}")
        print(f"Val   loss={val_loss:.4f} acc={val_acc:.4f} prec={val_prec:.4f} rec={val_rec:.4f} f1={val_f1:.4f}")

        # use weighted F1 (or val_acc) as selection metric
        current_metric = val_f1
        if current_metric > best_val_metric:
            best_val_metric = current_metric
            best_epoch = epoch
            torch.save({
                'model_state_dict': model.state_dict(),
                'tokenizer': MODEL_NAME,
                'config': {
                    'max_len': MAX_LEN,
                    'model_name': MODEL_NAME
                }
            }, best_model_path)
            print("Saved best model to", best_model_path)
            patience_counter = 0
        else:
            patience_counter += 1

        if patience_counter >= PATIENCE:
            print(f"Early stopping (no improvement in {PATIENCE} epochs).")
            break
        if val_acc >= TARGET_ACC:
            print(f"Target accuracy {TARGET_ACC:.2f} reached; stopping fold early.")
            break

    # Evaluate best saved model on validation set (optional reload to ensure correctness)
    # load state and eval
    checkpoint = torch.load(best_model_path, map_location=device)
    model.load_state_dict(checkpoint['model_state_dict'])
    _, val_acc, val_prec, val_rec, val_f1 = evaluate(model, val_loader, loss_fn, device)
    fold_metrics.append({
        'fold': fold,
        'best_epoch': best_epoch,
        'val_acc': val_acc,
        'val_precision': val_prec,
        'val_recall': val_rec,
        'val_f1': val_f1,
        'model_path': best_model_path
    })
    print(f"Fold {fold} best validation — acc: {val_acc:.4f}, prec: {val_prec:.4f}, rec: {val_rec:.4f}, f1: {val_f1:.4f}")

    # cleanup to free GPU mem
    del model, optimizer, scheduler, scaler
    torch.cuda.empty_cache()

# Summary across folds
avg_acc = np.mean([m['val_acc'] for m in fold_metrics])
avg_prec = np.mean([m['val_precision'] for m in fold_metrics])
avg_rec = np.mean([m['val_recall'] for m in fold_metrics])
avg_f1 = np.mean([m['val_f1'] for m in fold_metrics])

print("\n=== Cross-validation summary ===")
for m in fold_metrics:
    print(f"Fold {m['fold']}: acc={m['val_acc']:.4f}, prec={m['val_precision']:.4f}, rec={m['val_recall']:.4f}, f1={m['val_f1']:.4f}, saved={m['model_path']}")
print(f"Average — acc={avg_acc:.4f}, prec={avg_prec:.4f}, rec={avg_rec:.4f}, f1={avg_f1:.4f}")

# Print average metrics across all folds
print("\n=== Cross-validation summary ===")
print(f"Average — acc={avg_acc:.4f}, prec={avg_prec:.4f}, rec={avg_rec:.4f}, f1={avg_f1:.4f}")